# Generated by Django 5.0.4 on 2024-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDescription',
            field=models.CharField(error_messages={'required': 'Comment cannot be null'}, max_length=255),
        ),
    ]
