# Generated by Django 5.0.4 on 2024-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_commentdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDescription',
            field=models.CharField(max_length=255),
        ),
    ]
