# Generated by Django 5.0.4 on 2024-07-11 12:12

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.Post.upload_to),
        ),
    ]
